const API_URL="https://script.google.com/macros/s/AKfycbwYIXL6HtbCW6QiSediymQGV_zySDfcd0f-f61zJ2ihqeIFJ4h1C_Ge6T_zlaVWw3-M/exec",KEY="ankit_finance_hub_final_v3";let DB={},charts={};const $=x=>document.getElementById(x),uid=()=>Date.now()+"-"+Math.random().toString(36).slice(2),n=x=>Number(x||0)||0,m=x=>"₹"+n(x).toLocaleString("en-IN",{maximumFractionDigits:2}),ym=()=>new Date().toISOString().slice(0,7),today=()=>new Date().toISOString().slice(0,10);
async function api(action,payload={}){const r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,...payload})}),t=await r.text();let d;try{d=JSON.parse(t)}catch(e){throw Error("Invalid server response")};if(!d.success)throw Error(d.error||"Server error");return d}
function toast(x){$("toast").textContent=x;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2200)}function status(x){$("status").textContent=x}function cache(){localStorage.setItem(KEY,JSON.stringify(DB))}
async function loadAll(){try{status("☁️ Syncing...");DB=(await api("loadAll")).data||{};cache();render();status("☁️ Synced")}catch(e){status("⚠️ Sync Error");toast(e.message)}}
async function save(table,data){const r=await api("save",{table,data}),x=r.data.record;DB[table]=DB[table]||[];const i=DB[table].findIndex(z=>String(z.ID)===String(x.ID));i<0?DB[table].push(x):DB[table][i]=x;cache();render();toast("✓ Saved");return x}
async function del(table,id){if(!confirm("Delete this record?"))return;await api("delete",{table,id});DB[table]=(DB[table]||[]).filter(x=>x.ID!==id);cache();render();toast("Deleted")}
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));$(b.dataset.page).classList.add("active");$("sidebar").classList.remove("open")});$("menuBtn").onclick=()=>$("sidebar").classList.toggle("open");$("themeBtn").onclick=()=>{document.body.classList.toggle("dark");$("themeBtn").textContent=document.body.classList.contains("dark")?"☀️ Light":"🌙 Dark";draw()};
function card(a,b){return `<div><small>${a}</small><b>${b}</b></div>`}function item(a,b,c=""){return `<div class="item"><span>${a}</span><span>${b} ${c}</span></div>`}function chart(id,type,labels,data,label){if(!$(id))return;if(charts[id])charts[id].destroy();charts[id]=new Chart($(id),{type,data:{labels,datasets:[{label,data}]},options:{responsive:true,maintainAspectRatio:false}})}
function render(){dash();passbook();salary();loans();give();invest();split();vehicles();lists();draw()}
function dash(){const y=ym(),p=DB.passbook||[],s=DB.salary||[],e=DB.emi||[],pay=DB.sipPayments||[],inc=p.filter(x=>x.Date?.slice(0,7)===y&&x.Type==="Income").reduce((a,x)=>a+n(x.Amount),0),exp=p.filter(x=>x.Date?.slice(0,7)===y&&x.Type==="Expense").reduce((a,x)=>a+n(x.Amount),0),sal=s.filter(x=>x.Month===y).reduce((a,x)=>a+n(x.Amount),0),emi=e.filter(x=>x.Month===y).reduce((a,x)=>a+n(x.Amount),0),sip=pay.filter(x=>x.Month===y).reduce((a,x)=>a+n(x.Amount),0),b=Object.values(giveBal()),rec=b.filter(x=>x.balance>0).reduce((a,x)=>a+x.balance,0),owe=b.filter(x=>x.balance<0).reduce((a,x)=>a-x.balance,0);$("dash").innerHTML=[["💰 Salary",m(sal)],["💸 Expense",m(exp)],["📈 SIP Paid",m(sip)],["🏦 EMI Paid",m(emi)],["🤝 To Receive",m(rec)],["🤝 To Pay",m(owe)],["📒 Other Income",m(inc)],["💳 Net",m(sal+inc-exp-emi-sip)]].map(x=>card(...x)).join("")}
function passbook(){const p=DB.passbook||[],y=ym(),i=p.filter(x=>x.Date?.slice(0,7)===y&&x.Type==="Income").reduce((a,x)=>a+n(x.Amount),0),e=p.filter(x=>x.Date?.slice(0,7)===y&&x.Type==="Expense").reduce((a,x)=>a+n(x.Amount),0);$("passbookDash").innerHTML=[["Income",m(i)],["Expense",m(e)],["Net",m(i-e)],["Entries",p.length]].map(x=>card(...x)).join("");$("pbList").innerHTML=p.slice().reverse().map(x=>item(`${x.Date} • <b>${x.Category}</b> • ${x.Type}`,m(x.Amount),`<button class="danger" onclick="del('passbook','${x.ID}')">Delete</button>`)).join("")||"<p>No records</p>"}
function salary(){const s=DB.salary||[],y=ym(),cur=s.filter(x=>x.Month===y).reduce((a,x)=>a+n(x.Amount),0),tot=s.reduce((a,x)=>a+n(x.Amount),0);$("salaryDash").innerHTML=[["This Month",m(cur)],["Total",m(tot)],["Entries",s.length],["Companies",new Set(s.map(x=>x.Company)).size]].map(x=>card(...x)).join("");$("salaryList").innerHTML=s.slice().reverse().map(x=>item(`${x.Month} • ${x.Company}`,m(x.Amount),`<button class="danger" onclick="del('salary','${x.ID}')">Delete</button>`)).join("")||"<p>No salary records</p>"}
function loans(){const l=DB.loans||[],e=DB.emi||[],y=ym(),init=l.reduce((a,x)=>a+n(x["Initial Amount"]),0),paid=e.reduce((a,x)=>a+n(x.Amount),0),month=e.filter(x=>x.Month===y).reduce((a,x)=>a+n(x.Amount),0);$("loanDash").innerHTML=[["Initial Loans",m(init)],["EMI This Month",m(month)],["Total EMI Paid",m(paid)],["Loans",l.length]].map(x=>card(...x)).join("");$("emiLoan").innerHTML=`<option value="">Select loan</option>`+l.map(x=>`<option value="${x.ID}">${x["Loan Name"]}</option>`).join("");$("loanList").innerHTML=l.map(x=>{const p=e.filter(z=>z["Loan ID"]===x.ID).reduce((a,z)=>a+n(z.Amount),0);return item(`<b>${x["Loan Name"]}</b><br><small>Initial ${m(x["Initial Amount"])} • Paid ${m(p)} • Remaining ${m(Math.max(0,n(x["Initial Amount"])-p))}</small>`,"",`<button class="danger" onclick="del('loans','${x.ID}')">Delete</button>`)}).join("")||"<p>No loans</p>"}
function giveBal(){const o={};(DB.transactions||[]).forEach(x=>{const p=x.Person||"Unknown";if(!o[p])o[p]={person:p,balance:0,given:0,received:0,taken:0,paid:0};const a=n(x.Amount),z=o[p];if(x.Type==="Give"){z.balance+=a;z.given+=a}else if(x.Type==="Receive"){z.balance-=a;z.received+=a}else if(x.Type==="Take"){z.balance-=a;z.taken+=a}else if(x.Type==="Pay"){z.balance+=a;z.paid+=a}});return o}
function give(){const a=Object.values(giveBal()),r=a.filter(x=>x.balance>0).reduce((s,x)=>s+x.balance,0),p=a.filter(x=>x.balance<0).reduce((s,x)=>s-x.balance,0);$("giveDash").innerHTML=[["To Receive",m(r)],["To Pay",m(p)],["Net",m(r-p)],["People",a.length]].map(x=>card(...x)).join("");$("gtDashboard").innerHTML=a.map(x=>card(`${x.person} • ${x.balance>0?"To Receive":x.balance<0?"To Pay":"Settled"}`,m(Math.abs(x.balance)))).join("");$("gtList").innerHTML=(DB.transactions||[]).slice().reverse().map(x=>item(`<b>${x.Person}</b> • ${x.Type}<br><small>${x.Date||""} • ${x.Purpose||""}</small>`,m(x.Amount),`<button class="danger" onclick="del('transactions','${x.ID}')">Delete</button>`)).join("")||"<p>No records</p>"}
function invest(){const b=DB.baskets||[],a=DB.assets||[],p=DB.sipPayments||[],plan=a.reduce((s,x)=>s+n(x["Monthly Amount"]),0),paid=p.filter(x=>x.Month===ym()).reduce((s,x)=>s+n(x.Amount),0);$("investmentDash").innerHTML=[["Monthly Planned",m(plan)],["Paid",m(paid)],["Pending",m(Math.max(0,plan-paid))],["Baskets",b.length]].map(x=>card(...x)).join("");$("assetBasket").innerHTML=`<option value="">Select basket</option>`+b.map(x=>`<option value="${x.ID}">${x["Basket Name"]}</option>`).join("");$("basketList").innerHTML=b.map(x=>{const as=a.filter(z=>z["Basket ID"]===x.ID),t=as.reduce((s,z)=>s+n(z["Monthly Amount"]),0),done=p.some(z=>z["Basket ID"]===x.ID&&z.Month===ym());return item(`<b>${x["Basket Name"]}</b><br><small>${as.map(z=>z["Asset Name"]).join(", ")}</small>`,m(t),done?"✓ PAID":`<button onclick="markBasket('${x.ID}',${t})">Mark Paid</button>`)}).join("")||"<p>No baskets</p>"}

/* VEHICLE TRACKER */
function vehicles(){
const vs=DB.vehicles||[], fuel=DB.fuel||[], maint=DB.maintenance||[];
const prevFuel=$("fuelVehicle").value, prevMaint=$("maintVehicle").value;
const opts=`<option value="">Select vehicle</option>`+vs.map(v=>`<option value="${v.ID}">${v["Vehicle Name"]} • ${v["Vehicle Type"]}</option>`).join("");
$("fuelVehicle").innerHTML=opts;$("maintVehicle").innerHTML=opts;
if(vs.some(v=>v.ID===prevFuel))$("fuelVehicle").value=prevFuel;
if(vs.some(v=>v.ID===prevMaint))$("maintVehicle").value=prevMaint;

const fuelTotal=fuel.reduce((s,x)=>s+n(x.Amount),0);
const maintTotal=maint.reduce((s,x)=>s+n(x.Amount),0);
const month=ym();
const monthFuel=fuel.filter(x=>String(x.Date||"").slice(0,7)===month).reduce((s,x)=>s+n(x.Amount),0);
const monthMaint=maint.filter(x=>String(x.Date||"").slice(0,7)===month).reduce((s,x)=>s+n(x.Amount),0);

$("vehicleDash").innerHTML=[
["Vehicles",vs.length],["Fuel This Month",m(monthFuel)],["Maintenance This Month",m(monthMaint)],
["Total Fuel",m(fuelTotal)],["Total Maintenance",m(maintTotal)],["Total Vehicle Cost",m(fuelTotal+maintTotal)]
].map(x=>card(...x)).join("");

$("fuelList").innerHTML=fuel.slice().sort((a,b)=>String(b.Date).localeCompare(String(a.Date))).map(x=>{
const v=vs.find(z=>z.ID===x["Vehicle ID"]);
return item(`<b>${v?v["Vehicle Name"]:"Unknown Vehicle"}</b><br><small>${x.Date} • ${x.Odometer||"-"} km • ${x["Fuel Quantity"]||0} L • ${x["Fuel Type"]||"Fuel"} • ${x.Notes||""}</small>`,m(x.Amount),`<button class="danger" onclick="del('fuel','${x.ID}')">Delete</button>`);
}).join("")||"<p>No fuel entries</p>";

$("maintenanceList").innerHTML=maint.slice().sort((a,b)=>String(b.Date).localeCompare(String(a.Date))).map(x=>{
const v=vs.find(z=>z.ID===x["Vehicle ID"]);
return item(`<b>${v?v["Vehicle Name"]:"Unknown Vehicle"}</b><br><small>${x.Date} • ${x.Category} • ${x.Odometer||"-"} km • ${x.Remarks||""}</small>`,m(x.Amount),`<button class="danger" onclick="del('maintenance','${x.ID}')">Delete</button>`);
}).join("")||"<p>No maintenance entries</p>";
}

function addVehicle(){
const name=$("vehicleName").value.trim();
if(!name)return toast("Enter vehicle name");
return save("vehicles",{ID:uid(),"Vehicle Name":name,"Vehicle Type":$("vehicleType").value,"Number Plate":$("vehiclePlate").value.trim()});
}
function addFuel(){
if(!$("fuelVehicle").value)return toast("Select vehicle");
const amount=n($("fuelAmount").value);
if(amount<=0)return toast("Enter valid fuel amount");
return save("fuel",{ID:uid(),"Vehicle ID":$("fuelVehicle").value,Date:$("fuelDate").value||today(),Odometer:n($("fuelOdo").value),"Fuel Quantity":n($("fuelQty").value),Amount:amount,"Fuel Type":$("fuelType").value,Notes:$("fuelNotes").value}).then(r=>save("passbook",{ID:r.ID,Date:r.Date,Type:"Expense",Category:"Petrol / Fuel",Amount:amount,Account:"Vehicle Tracker",Remarks:(DB.vehicles||[]).find(v=>v.ID===r["Vehicle ID"])?.["Vehicle Name"]||"Fuel"}));
}
function addMaintenance(){
if(!$("maintVehicle").value)return toast("Select vehicle");
const amount=n($("maintAmount").value);
if(amount<=0)return toast("Enter valid maintenance amount");
return save("maintenance",{ID:uid(),"Vehicle ID":$("maintVehicle").value,Date:$("maintDate").value||today(),Category:$("maintCategory").value,Amount:amount,Odometer:n($("maintOdo").value),Remarks:$("maintRemarks").value}).then(r=>save("passbook",{ID:r.ID,Date:r.Date,Type:"Expense",Category:"Vehicle Maintenance",Amount:amount,Account:"Vehicle Tracker",Remarks:`${r.Category} - ${(DB.vehicles||[]).find(v=>v.ID===r["Vehicle ID"])?.["Vehicle Name"]||"Vehicle"}`}));
}

/* Splitwise */
const members=g=>{try{return JSON.parse(g["Members JSON"]||"[]")}catch(e){return[]}},json=(x,d=[])=>{try{return JSON.parse(x||"")}catch(e){return d}};
function calc(g){const st={};members(g).forEach(x=>st[x]={name:x,paid:0,share:0,out:0,in:0,net:0});const ex=(DB.splitExpenses||[]).filter(x=>x["Group ID"]===g.ID);ex.forEach(e=>{const a=n(e.Amount),payer=e["Paid By"];if(!st[payer])st[payer]={name:payer,paid:0,share:0,out:0,in:0,net:0};st[payer].paid+=a;let ps=json(e["Members JSON"],[]);if(!ps.length)ps=members(g);const cs=json(e["Custom Shares JSON"],null);ps.forEach(x=>{if(!st[x])st[x]={name:x,paid:0,share:0,out:0,in:0,net:0};st[x].share+=cs?n(cs[x]):a/ps.length})});(DB.splitSettlements||[]).filter(x=>x["Group ID"]===g.ID).forEach(s=>{if(st[s.From])st[s.From].out+=n(s.Amount);if(st[s.To])st[s.To].in+=n(s.Amount)});Object.values(st).forEach(x=>x.net=x.paid-x.share+x.out-x.in);return{ex,st:Object.values(st),total:ex.reduce((s,x)=>s+n(x.Amount),0)}}
function settle(st){let c=st.filter(x=>x.net>.01).map(x=>({name:x.name,a:x.net})),d=st.filter(x=>x.net<-.01).map(x=>({name:x.name,a:-x.net})),o=[],i=0,j=0;while(i<d.length&&j<c.length){let a=Math.min(d[i].a,c[j].a);o.push({from:d[i].name,to:c[j].name,amount:a});d[i].a-=a;c[j].a-=a;if(d[i].a<.01)i++;if(c[j].a<.01)j++}return o}
function split(){const gs=DB.splitGroups||[],id=$("spGroupSel").value||gs[0]?.ID||"",opts=`<option value="">Select group</option>`+gs.map(g=>`<option value="${g.ID}">${g["Group Name"]}</option>`).join("");$("spGroupSel").innerHTML=opts;$("spGroupExpense").innerHTML=opts;$("spGroupSel").value=id;$("spGroupExpense").value=id;const g=gs.find(x=>x.ID===id);if(!g){$("splitSummary").innerHTML="";return}const ms=members(g);$("spPaidBy").innerHTML=`<option value="">Paid by</option>`+ms.map(x=>`<option>${x}</option>`).join("");$("memberChips").innerHTML=ms.map(x=>`<span class="chip">${x}<button class="danger" onclick="removeMember('${x}')">×</button></span>`).join("");const c=calc(g);$("splitSummary").innerHTML=[["Total Expenses",m(c.total)],["Expenses",c.ex.length],...c.st.map(x=>[`${x.name} • ${x.net>0?"Receive":x.net<0?"Pay":"Settled"}`,m(Math.abs(x.net))])].map(x=>card(...x)).join("");$("settlementList").innerHTML=settle(c.st).map(x=>item(`<b>${x.from}</b> → <b>${x.to}</b>`,m(x.amount),`<button class="success" onclick="settleNow('${g.ID}','${x.from}','${x.to}',${x.amount})">Mark Settled</button>`)).join("")||"<p>🎉 Everyone is settled!</p>";$("splitExpenseList").innerHTML=c.ex.slice().reverse().map(x=>item(`<b>${x.Title}</b><br><small>${x.Date} • Paid by ${x["Paid By"]} • ${json(x["Members JSON"],[]).join(", ")}</small>`,m(x.Amount),`<button class="secondary" onclick="editExpense('${x.ID}')">Edit</button> <button class="danger" onclick="del('splitExpenses','${x.ID}')">Delete</button>`)).join("")||"<p>No expenses</p>";$("splitSettlementHistory").innerHTML=(DB.splitSettlements||[]).filter(x=>x["Group ID"]===g.ID).slice().reverse().map(x=>item(`<b>${x.From}</b> paid <b>${x.To}</b><br><small>${x.Date}</small>`,m(x.Amount),`<button class="danger" onclick="del('splitSettlements','${x.ID}')">Delete</button>`)).join("")||"<p>No settlements</p>";$("splitList").innerHTML=gs.map(x=>`<div class="item"><span><b>${x["Group Name"]}</b><br><small>${members(x).join(", ")}</small></span><button class="secondary" onclick="openGroup('${x.ID}')">Open</button></div>`).join("");shares()}
function openGroup(id){$("spGroupSel").value=id;$("spGroupExpense").value=id;split();draw()}function shares(){if($("spSplitType").value!=="custom")return $("customShares").innerHTML="";const g=(DB.splitGroups||[]).find(x=>x.ID===$("spGroupExpense").value);if(!g)return;let ps=$("spMembersSel").value.split(",").map(x=>x.trim()).filter(Boolean);if(!ps.length)ps=members(g);$("customShares").innerHTML=ps.map(x=>`<div class="share"><span>${x}</span><input class="shareamt" data-name="${x}" type="number" placeholder="Amount"></div>`).join("")}
async function addGroup(){const name=$("spGroup").value.trim(),ms=$("spMembers").value.split(",").map(x=>x.trim()).filter(Boolean);if(!name||ms.length<2)return toast("Enter group name and minimum 2 members");const g=await save("splitGroups",{ID:uid(),"Group Name":name,Category:$("spCat").value,"Members JSON":JSON.stringify([...new Set(ms)])});$("spGroup").value="";$("spMembers").value="";openGroup(g.ID)}
async function addMember(){const g=(DB.splitGroups||[]).find(x=>x.ID===$("spGroupSel").value),x=$("newMember").value.trim();if(!g||!x)return toast("Select group and enter member");const ms=members(g);if(ms.includes(x))return toast("Already added");await save("splitGroups",{...g,"Members JSON":JSON.stringify([...ms,x])});$("newMember").value=""}
async function removeMember(x){const g=(DB.splitGroups||[]).find(x=>x.ID===$("spGroupSel").value);if(!g||!confirm(`Remove ${x}?`))return;await save("splitGroups",{...g,"Members JSON":JSON.stringify(members(g).filter(z=>z!==x))})}
async function renameGroup(){const g=(DB.splitGroups||[]).find(x=>x.ID===$("spGroupSel").value),x=prompt("Group name",g?.["Group Name"]);if(x?.trim())await save("splitGroups",{...g,"Group Name":x.trim()})}
function clearSplit(){$("splitEditId").value="";$("spTitle").value="";$("spAmount").value="";$("spMembersSel").value="";$("spDate").value=today();$("spSplitType").value="equal";$("customShares").innerHTML=""}
function editExpense(id){const e=(DB.splitExpenses||[]).find(x=>x.ID===id);$("splitEditId").value=id;$("spGroupExpense").value=e["Group ID"];$("spTitle").value=e.Title;$("spAmount").value=e.Amount;$("spPaidBy").value=e["Paid By"];$("spDate").value=e.Date;$("spMembersSel").value=json(e["Members JSON"],[]).join(", ");$("spSplitType").value=e["Custom Shares JSON"]?"custom":"equal";shares();const c=json(e["Custom Shares JSON"],{});document.querySelectorAll(".shareamt").forEach(i=>i.value=n(c[i.dataset.name]))}
async function saveSplitExpense(){const g=(DB.splitGroups||[]).find(x=>x.ID===$("spGroupExpense").value),a=n($("spAmount").value),payer=$("spPaidBy").value;if(!g||a<=0||!payer)return toast("Select group, payer and amount");let ps=$("spMembersSel").value.split(",").map(x=>x.trim()).filter(Boolean);if(!ps.length)ps=members(g);let custom="";if($("spSplitType").value==="custom"){let o={};document.querySelectorAll(".shareamt").forEach(i=>o[i.dataset.name]=n(i.value));if(Math.abs(Object.values(o).reduce((s,x)=>s+x,0)-a)>.01)return toast("Custom total must equal expense amount");custom=JSON.stringify(o)}await save("splitExpenses",{ID:$("splitEditId").value||uid(),"Group ID":g.ID,Title:$("spTitle").value||"Expense",Amount:a,"Paid By":payer,"Members JSON":JSON.stringify(ps),"Custom Shares JSON":custom,Date:$("spDate").value||today()});clearSplit()}
async function settleNow(g,f,t,a){if(confirm(`${f} paid ${m(a)} to ${t}?`))await save("splitSettlements",{ID:uid(),"Group ID":g,From:f,To:t,Amount:a,Date:today(),Notes:"Settlement"})}
function lists(){const p=DB.passbook||[],s=DB.salary||[],t=DB.transactions||[];const fill=(id,a)=>{const e=$(id);if(e)e.innerHTML=[...new Set(a.filter(Boolean))].map(x=>`<option value="${x}">`).join("")};fill("categoryList",p.map(x=>x.Category));fill("accountList",p.map(x=>x.Account));fill("remarksList",p.map(x=>x.Remarks));fill("companyList",s.map(x=>x.Company));fill("salaryRemarksList",s.map(x=>x.Remarks));fill("personList",t.map(x=>x.Person));fill("vehicleNameList",(DB.vehicles||[]).map(x=>x["Vehicle Name"]))}
function draw(){const y=ym(),p=DB.passbook||[],s=DB.salary||[],e=DB.emi||[],l=DB.loans||[],a=DB.assets||[],inc=p.filter(x=>x.Date?.slice(0,7)===y&&x.Type==="Income").reduce((z,x)=>z+n(x.Amount),0),exp=p.filter(x=>x.Date?.slice(0,7)===y&&x.Type==="Expense").reduce((z,x)=>z+n(x.Amount),0),sal=s.filter(x=>x.Month===y).reduce((z,x)=>z+n(x.Amount),0),em=e.filter(x=>x.Month===y).reduce((z,x)=>z+n(x.Amount),0);chart("mainChart","bar",["Salary","Income","Expense","EMI"],[sal,inc,exp,em],"Amount");chart("expenseChart","doughnut",["Income","Expense"],[inc,exp],"Amount");chart("passbookChart","bar",["Income","Expense"],[inc,exp],"Amount");const sm={};s.forEach(x=>sm[x.Month]=(sm[x.Month]||0)+n(x.Amount));chart("salaryChart","line",Object.keys(sm),Object.values(sm),"Salary");chart("loanChart","doughnut",["Initial","EMI Paid"],[l.reduce((z,x)=>z+n(x["Initial Amount"]),0),e.reduce((z,x)=>z+n(x.Amount),0)],"Amount");const gb=Object.values(giveBal());chart("giveChart","bar",gb.map(x=>x.person),gb.map(x=>Math.abs(x.balance)),"Outstanding");const g=(DB.splitGroups||[]).find(x=>x.ID===$("spGroupSel").value);if(g){const c=calc(g);chart("splitChart","bar",c.st.map(x=>x.name),c.st.map(x=>x.paid),"Paid")}chart("investmentChart","doughnut",a.map(x=>x["Asset Name"]),a.map(x=>n(x["Monthly Amount"])),"Monthly Amount");
const vs=DB.vehicles||[],fu=DB.fuel||[],ma=DB.maintenance||[];
chart("fuelChart","bar",vs.map(v=>v["Vehicle Name"]),vs.map(v=>fu.filter(x=>x["Vehicle ID"]===v.ID).reduce((z,x)=>z+n(x.Amount),0)),"Fuel Cost");
chart("maintenanceChart","bar",vs.map(v=>v["Vehicle Name"]),vs.map(v=>ma.filter(x=>x["Vehicle ID"]===v.ID).reduce((z,x)=>z+n(x.Amount),0)),"Maintenance Cost") }
function addPassbook(){return save("passbook",{ID:uid(),Date:$("pbDate").value||today(),Type:$("pbType").value,Category:$("pbCat").value,Amount:n($("pbAmt").value),Account:$("pbAccount").value,Remarks:$("pbRemarks").value})}function addSalary(){return save("salary",{ID:uid(),Month:$("salMonth").value||ym(),Company:$("salCompany").value,Amount:n($("salAmount").value),Remarks:$("salRemarks").value})}function addLoan(){return save("loans",{ID:uid(),"Loan Name":$("loanName").value,"Initial Amount":n($("loanInitial").value),Remarks:$("loanRemarks").value})}function addEmi(){if(!$("emiLoan").value)return toast("Select loan");return save("emi",{ID:uid(),"Loan ID":$("emiLoan").value,Month:$("emiMonth").value||ym(),Amount:n($("emiAmount").value),Remarks:$("emiRemarks").value})}function addGive(){return save("transactions",{ID:uid(),Person:$("gtPerson").value,Type:$("gtType").value,Amount:n($("gtAmount").value),Date:$("gtDate").value||today(),Purpose:$("gtPurpose").value,Notes:$("gtNotes").value,Revisions:"[]"})}
async function addBasket(){const name=$("sipPerson").value.trim(),basket=$("sipBasket").value.trim();if(!name||!basket)return toast("Enter person and basket");let p=(DB.people||[]).find(x=>x.Name===name);if(!p)p=await save("people",{ID:uid(),Name:name});await save("baskets",{ID:uid(),"Person ID":p.ID,"Basket Name":basket})}function addAsset(){if(!$("assetBasket").value)return toast("Select basket");return save("assets",{ID:uid(),"Basket ID":$("assetBasket").value,"Asset Name":$("assetName").value,"Asset Type":$("assetType").value,"Monthly Amount":n($("assetAmount").value)})}function markBasket(id,total){return save("sipPayments",{ID:uid(),"Basket ID":id,Month:ym(),Amount:total,"Paid At":new Date().toISOString()})}
$("spGroupSel").onchange=()=>openGroup($("spGroupSel").value);$("spGroupExpense").onchange=()=>openGroup($("spGroupExpense").value);$("spSplitType").onchange=shares;$("spMembersSel").onchange=shares;["pbDate","gtDate","spDate","fuelDate","maintDate"].forEach(x=>$(x).value=today());["salMonth","emiMonth"].forEach(x=>$(x).value=ym());try{DB=JSON.parse(localStorage.getItem(KEY)||"{}")}catch(e){}if(Object.keys(DB).length){render();status("☁️ Loading...")}loadAll();
